services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=mongodb://mongo:27017/node-auth
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
